### PR TITLE
fixes for support and perf

### LINKED ISSUE #1060: on a failed cluster, the support terms need accepting
otherwise the cluster will fail to destroy

### PR DESCRIPTION
**Pull request by anhowe**
* fixes #1060 on destroy
* understanding two perf issues, and need a temporary change to vfxt.py (no upstream plans at the moment, unless it leads to discovery)

### CODE REVIEW

**Comment by jswoodward** [comment]
What issue is this addressing? What are the plans for upstream?

**Comment by anhowe** [comment]
> What issue is this addressing? What are the plans for upstream?

I updated the description.  No plans for upstream at the moment, as just trying to understand better two perf issues

**Comment by jswoodward** [comment]
>     * fixes #1061 on destroy
> 
>     * understanding two perf issues, and need a temporary change to vfxt.py (no upstream plans at the moment, unless it leads to discovery)

Specifying cache size and disk sizes/counts/etc is redundant. Please specify disk count and sizes. If we need to then change the default we can upstream that change. Otherwise mixing node cache auto sizing + manual size/count is not going to be supported.

**Comment by anhowe** [comment]
> > ```
> > * fixes #1061 on destroy
> > 
> > * understanding two perf issues, and need a temporary change to vfxt.py (no upstream plans at the moment, unless it leads to discovery)
> > ```
> 
> Specifying cache size and disk sizes/counts/etc is redundant. Please specify disk count and sizes. If we need to then change the default sizing when cache size is specified we can upstream that change. Otherwise we are not going to support both node cache auto sizing + manual size/count as that is redundant.

Thanks, this is now updated to correctly use the parameters, and I was able to eliminate the controller changes.

**Review by baileye — APPROVED** [review]

**Pull request merged**
